/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'

const StoriesLazyRouteImport = createFileRoute('/stories')()
const IndexLazyRouteImport = createFileRoute('/')()
const StoriesStoryIdLazyRouteImport = createFileRoute('/stories/$storyId')()

const StoriesLazyRoute = StoriesLazyRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/stories.lazy').then((d) => d.Route))
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/map.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const StoriesStoryIdLazyRoute = StoriesStoryIdLazyRouteImport.update({
  id: '/$storyId',
  path: '/$storyId',
  getParentRoute: () => StoriesLazyRoute,
} as any).lazy(() =>
  import('./routes/stories/$storyId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/map': typeof MapRoute
  '/stories': typeof StoriesLazyRouteWithChildren
  '/stories/$storyId': typeof StoriesStoryIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/map': typeof MapRoute
  '/stories': typeof StoriesLazyRouteWithChildren
  '/stories/$storyId': typeof StoriesStoryIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/map': typeof MapRoute
  '/stories': typeof StoriesLazyRouteWithChildren
  '/stories/$storyId': typeof StoriesStoryIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map' | '/stories' | '/stories/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map' | '/stories' | '/stories/$storyId'
  id: '__root__' | '/' | '/map' | '/stories' | '/stories/$storyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MapRoute: typeof MapRoute
  StoriesLazyRoute: typeof StoriesLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdLazyRouteImport
      parentRoute: typeof StoriesLazyRoute
    }
  }
}

interface StoriesLazyRouteChildren {
  StoriesStoryIdLazyRoute: typeof StoriesStoryIdLazyRoute
}

const StoriesLazyRouteChildren: StoriesLazyRouteChildren = {
  StoriesStoryIdLazyRoute: StoriesStoryIdLazyRoute,
}

const StoriesLazyRouteWithChildren = StoriesLazyRoute._addFileChildren(
  StoriesLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MapRoute: MapRoute,
  StoriesLazyRoute: StoriesLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
